### ISSUE TITLE
Error 500 with owner birth date 29.02 not in a leap year

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#1005]
date 29.02.2003 doesn't exist.
I expect Error 422 validation_failed, "description": "invalid birth_date value"

## Request 
```
{
  "signed_legal_entity_request":
"MIIZcgYJKoZIhvcNAQcCoIIZYzCCGV8CAQExDjAMBgoqhiQCAQEBAQIBMIIKAAYJKoZIhvcNAQcBoIIJ8QSCCe17DQogICAgIm5hbWUiOiAi0JDQv9GC0LXQutCwINCU0L7QsdGA0L7Qs9C+INCU0L3RjyIsDQogICAgInNob3J0X25hbWUiOiAi0JTQvtCx0YDQvtCz0L4g0JTQvdGPIiwNCiAgICAicHVibGljX25hbWUiOiAi0JTQvtCx0YDQvtCz0L4g0JTQvdGPIiwNCiAgICAidHlwZSI6ICJQSEFSTUFDWSIsDQogICAgIm93bmVyX3Byb3BlcnR5X3R5cGUiOiAiU1RBVEUiLA0KICAgICJsZWdhbF9mb3JtIjogIjE0MCIsDQogICAgImVkcnBvdSI6ICIzODc4MjMyMyIsDQogICAgImt2ZWRzIjogWw0KICAgICAgICAiNDcuNzMiLCI2My45OSIsIjAxLjExIg0KICAgIF0sDQogICAgImFkZHJlc3NlcyI6IFsNCiAgICAgICAgew0KICAgICAgICAgICAgInR5cGUiOiAiUkVHSVNUUkFUSU9OIiwNCiAgICAgICAgICAgICJjb3VudHJ5IjogIlVBIiwNCiAgICAgICAgICAgICJhcmVhIjogItCl0JDQoNCa0IbQktCh0KzQmtCQIiwNCiAgICAgICAgICAgICJzZXR0bGVtZW50IjogItCn0KPQk9Cj0IfQkiIsDQogICAgICAgICAgICAic2V0dGxlbWVudF90eXBlIjogIkNJVFkiLA0KICAgICAgICAgICAgInNldHRsZW1lbnRfaWQiOiAiZmI1ZTZmMDctMGMyZC00YzVjLThiYzUtZjBiODZiYjk0NDk0IiwNCiAgICAgICAgICAgICJzdHJlZXRfdHlwZSI6ICJTVFJFRVQiLA0KICAgICAgICAgICAgInN0cmVldCI6ICLQstGD0LsuINCd0ZbQttC40L3RgdGM0LrQsCIsDQogICAgICAgICAgICAiYnVpbGRpbmciOiAiMTUiLA0KICAgICAgICAgICAgImFwYXJ0bWVudCI6ICIyMyIsDQogICAgICAgICAgICAiemlwIjogIjAyMDkwIg0KICAgICAgICB9DQogICAgXSwNCiAgICAicGhvbmVzIjogWw0KICAgICAgICB7DQogICAgICAgICAgICAidHlwZSI6ICJNT0JJTEUiLA0KICAgICAgICAgICAgIm51bWJlciI6ICIrMzgwNTAzNDEwODcwIg0KICAgICAgICB9DQogICAgXSwNCiAgICAiZW1haWwiOiAic3ZldGF2ZWRtZWQrMjJAZ21haWwuY29tIiwNCiAgICAib3duZXIiOiB7DQogICAgICAgICJmaXJzdF9uYW1lIjogItCf0LXRgtGA0L4iLA0KICAgICAgICAibGFzdF9uYW1lIjogItCG0LLQsNC90L7QsiIsDQogICAgICAgICJzZWNvbmRfbmFtZSI6ICLQnNC40LrQvtC70LDQudC+0LLQuNGHIiwNCiAgICAgICAgInRheF9pZCI6ICIyOTg4MTIwOTUzIiwNCiAgICAgICAgImJpcnRoX2RhdGUiOiAiMjAxNC0wMi0yOSIsDQogICAgICAgICJiaXJ0aF9wbGFjZSI6ICLQktGW0L3QvdC40YbRjywg0KPQutGA0LDRl9C90LAiLA0KICAgICAgICAiZ2VuZGVyIjogIkZFTUFMRSIsDQogICAgICAgICJlbWFpbCI6ICJzdmV0YXZlZG1lZCsyM0BnbWFpbC5jb20iLA0KICAgICAgICAiZG9jdW1lbnRzIjogWw0KICAgICAgICAgICAgew0KICAgICAgICAgICAgICAgICJ0eXBlIjogIlBBU1NQT1JUIiwNCiAgICAgICAgICAgICAgICAibnVtYmVyIjogIjEyMDUxOCINCiAgICAgICAgICAgIH0NCiAgICAgICAgXSwNCiAgICAgICAgInBob25lcyI6IFsNCiAgICAgICAgICAgIHsNCiAgICAgICAgICAgICAgICAidHlwZSI6ICJNT0JJTEUiLA0KICAgICAgICAgICAgICAgICJudW1iZXIiOiAiKzM4MDUwMzQxMDg3MCINCiAgICAgICAgICAgIH0NCiAgICAgICAgXSwNCiAgICAgICAgInBvc2l0aW9uIjogIlAxIg0KICAgIH0sDQogICAgIm1lZGljYWxfc2VydmljZV9wcm92aWRlciI6IHsNCiAgICAgICAgImxpY2Vuc2VzIjogWw0KICAgICAgICAgICAgew0KICAgICAgICAgICAgICAgICJsaWNlbnNlX251bWJlciI6ICJmZDEyMzQ0MyIsDQogICAgICAgICAgICAgICAgImlzc3VlZF9ieSI6ICLQmtCy0LDQu9GW0YTRltC60LDRhtC50L3QsCDQutC+0LzRltGB0ZbRjyIsDQogICAgICAgICAgICAgICAgImlzc3VlZF9kYXRlIjogIjE5OTEtMDgtMTkiLA0KICAgICAgICAgICAgICAgICJleHBpcnlfZGF0ZSI6ICIxOTkxLTA4LTE5IiwNCiAgICAgICAgICAgICAgICAiYWN0aXZlX2Zyb21fZGF0ZSI6ICIxOTkxLTA4LTE5IiwNCiAgICAgICAgICAgICAgICAid2hhdF9saWNlbnNlZCI6ICLRgNC10LDQu9GW0LfQsNGG0ZbRjyDQvdCw0YDQutC+0YLQuNGH0L3QuNGFINC30LDRgdC+0LHRltCyIiwNCiAgICAgICAgICAgICAgICAib3JkZXJfbm8iOiAi0JotMTIzIg0KICAgICAgICAgICAgfQ0KICAgICAgICBdLA0KICAgICAgICAiYWNjcmVkaXRhdGlvbiI6IHsNCiAgICAgICAgICAgICJjYXRlZ29yeSI6ICJGSVJTVCIsDQogICAgICAgICAgICAiaXNzdWVkX2RhdGUiOiAiMTk5MS0wOC0xOSIsDQogICAgICAgICAgICAiZXhwaXJ5X2RhdGUiOiAiMTk5MS0wOC0xOSIsDQogICAgICAgICAgICAib3JkZXJfbm8iOiAiZmQxMjM0NDMiLA0KICAgICAgICAgICAgIm9yZGVyX2RhdGUiOiAiMTk5MS0wOC0xOSINCiAgICAgICAgfQ0KICAgIH0sDQogICAgInNlY3VyaXR5Ijogew0KICAgICAgICAicmVkaXJlY3RfdXJpIjogImh0dHA6Ly9leGFtcGxlMi5jb20iDQogICAgfSwNCiAgICAicHVibGljX29mZmVyIjogew0KICAgICAgICAiY29uc2VudCI6IHRydWUsDQogICAgICAgICJjb25zZW50X3RleHQiOiAiQ29uc2VudCB0ZXh0Ig0KICAgIH0NCn2gggctMIIHKTCCBtGgAwIBAgIUM7bLe/chuc4EAAAAfcMhAElhTwAwDQYLKoYkAgEBAQEDAQEwggFQMVQwUgYDVQQKDEvQhtC90YTQvtGA0LzQsNGG0ZbQudC90L4t0LTQvtCy0ZbQtNC60L7QstC40Lkg0LTQtdC/0LDRgNGC0LDQvNC10L3RgiDQlNCk0KExXjBcBgNVBAsMVdCj0L/RgNCw0LLQu9GW0L3QvdGPICjRhtC10L3RgtGAKSDRgdC10YDRgtC40YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyINCG0JTQlCDQlNCk0KExYjBgBgNVBAMMWdCQ0LrRgNC10LTQuNGC0L7QstCw0L3QuNC5INGG0LXQvdGC0YAg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiDQhtCU0JQg0JTQpNChMRQwEgYDVQQFDAtVQS0zOTM4NDQ3NjELMAkGA1UEBhMCVUExETAPBgNVBAcMCNCa0LjRl9CyMB4XDTE3MDExNzIyMDAwMFoXDTE5MDExNzIyMDAwMFowgd8xPDA6BgNVBAoMM9Ci0J7QkiAi0JXQpNCG0KIg0KLQldCa0J3QntCb0J7QlNCW0IbQoSIgKNCi0JXQodCiKTERMA8GA1UECwwI0KLQtdGB0YIxETAPBgNVBAwMCNGC0LXRgdGCMRgwFgYDVQQDDA/QotC10YHRgiDQoi7Qoi4xETAPBgNVBAQMCNCi0LXRgdGCMRowGAYDVQQqDBHQotC10YHRgiDQotC10YHRgjEQMA4GA1UEBQwHMjIxMjczMzELMAkGA1UEBhMCVUExETAPBgNVBAcMCNCa0LjRl9CyMIHyMIHJBgsqhiQCAQEBAQMBATCBuTB1MAcCAgEBAgEMAgEABCEQvuPbauqeH4ZXjEXBJZT/lCOUp9c4+Rh+ZRUBcpT0zgECIQCAAAAAAAAAAAAAAAAAAAAAZ1khOvGC6YfT4XcUkH1HDQQhtg/S2NzoqTQjxhAbypHEegB+bDALJs1VbJsOfSDvKSoABECp1utF8TxwgoDElnsjH16t9ljrpMA3KR042WvwJcpOF/jpcg3GFbQ6KJdfC8Heo2Q4tWTqLBef0BI+bbj6xXkEAyQABCGRg29rHiDv7uCN8L/DwKkjXSLgMLbsjKylp3NKmQMNIgCjggNYMIIDVDApBgNVHQ4EIgQgVC+0TaYBeQns+rQ7cGPx4TjW8HkqfFbyqwVtsLSBAsIwKwYDVR0jBCQwIoAgM7bLe/chuc7u494uYv7qO3AaS2dgvBwvzzVlFrUOvKowLwYDVR0QBCgwJqARGA8yMDE3MDExNzIyMDAwMFqhERgPMjAxOTAxMTcyMjAwMDBaMA4GA1UdDwEB/wQEAwIGwDAZBgNVHSABAf8EDzANMAsGCSqGJAIBAQECAjAMBgNVHRMBAf8EAjAAMB4GCCsGAQUFBwEDAQH/BA8wDTALBgkqhiQCAQEBAgEwgacGA1UdEQSBnzCBnKBNBgwrBgEEAYGXRgEBBAKgPQw7MDQwODYsINC8LiDQmtC40ZfQsiwg0LLRg9C7LiDQntC70LXQvdC4INCi0LXQu9GW0LPQuCwgMzkt0JCgJgYMKwYBBAGBl0YBAQQBoBYMFCszOCAoMCA0NCkgMzgzLTMyLTM3gRBpbmZvQGVmaXQuY29tLnVhoBEGCisGAQQBgjcUAgOgAwwBNjBIBgNVHR8EQTA/MD2gO6A5hjdodHRwOi8vYWNza2lkZC5nb3YudWEvZG93bmxvYWQvY3Jscy9BQ1NLSUREREZTLUZ1bGwuY3JsMEkGA1UdLgRCMEAwPqA8oDqGOGh0dHA6Ly9hY3NraWRkLmdvdi51YS9kb3dubG9hZC9jcmxzL0FDU0tJRERERlMtRGVsdGEuY3JsMIGIBggrBgEFBQcBAQR8MHowMAYIKwYBBQUHMAGGJGh0dHA6Ly9hY3NraWRkLmdvdi51YS9zZXJ2aWNlcy9vY3NwLzBGBggrBgEFBQcwAoY6aHR0cDovL2Fjc2tpZGQuZ292LnVhL2Rvd25sb2FkL2NlcnRpZmljYXRlcy9hbGxhY3NraWRkLnA3YjA/BggrBgEFBQcBCwQzMDEwLwYIKwYBBQUHMAOGI2h0dHA6Ly9hY3NraWRkLmdvdi51YS9zZXJ2aWNlcy90c3AvMGUGA1UdCQReMFwwGgYMKoYkAgEBAQsBBAIBMQoTCDM4NzgyMzIzMBwGDCqGJAIBAQELAQQBATEMEwoxMTExMTExMTExMCAGDCqGJAIBAQELAQQLATEQEw4xOTkxMDgyNC0wMDAyNjANBgsqhiQCAQEBAQMBAQNDAARADQ0mJ2T9yt4eG7VJC1w0NVIVY3AiNV6MLQ9PoV9+NzfcX8Fjqt+BvoWJTwKIJDUq44/Hq3aBofsabZ/arVIvGjGCCBMwgggPAgEBMIIBajCCAVAxVDBSBgNVBAoMS9CG0L3RhNC+0YDQvNCw0YbRltC50L3Qvi3QtNC+0LLRltC00LrQvtCy0LjQuSDQtNC10L/QsNGA0YLQsNC80LXQvdGCINCU0KTQoTFeMFwGA1UECwxV0KPQv9GA0LDQstC70ZbQvdC90Y8gKNGG0LXQvdGC0YApINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIg0IbQlNCUINCU0KTQoTFiMGAGA1UEAwxZ0JDQutGA0LXQtNC40YLQvtCy0LDQvdC40Lkg0YbQtdC90YLRgCDRgdC10YDRgtC40YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyINCG0JTQlCDQlNCk0KExFDASBgNVBAUMC1VBLTM5Mzg0NDc2MQswCQYDVQQGEwJVQTERMA8GA1UEBwwI0JrQuNGX0LICFDO2y3v3IbnOBAAAAH3DIQBJYU8AMAwGCiqGJAIBAQEBAgGgggY7MBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTE3MDkwNzA4MzY0OFowLwYJKoZIhvcNAQkEMSIEIOmBspF9pUTiIYLK3UocUsIq/Hco+wYT86OnLPfkWnAIMIIBwwYLKoZIhvcNAQkQAi8xggGyMIIBrjCCAaowggGmMAwGCiqGJAIBAQEBAgEEILtxymZ5x+HDuXMKEYOLmBH0ETRX+IoiHTlRw3Mn8m3QMIIBcjCCAVikggFUMIIBUDFUMFIGA1UECgxL0IbQvdGE0L7RgNC80LDRhtGW0LnQvdC+LdC00L7QstGW0LTQutC+0LLQuNC5INC00LXQv9Cw0YDRgtCw0LzQtdC90YIg0JTQpNChMV4wXAYDVQQLDFXQo9C/0YDQsNCy0LvRltC90L3RjyAo0YbQtdC90YLRgCkg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiDQhtCU0JQg0JTQpNChMWIwYAYDVQQDDFnQkNC60YDQtdC00LjRgtC+0LLQsNC90LjQuSDRhtC10L3RgtGAINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIg0IbQlNCUINCU0KTQoTEUMBIGA1UEBQwLVUEtMzkzODQ0NzYxCzAJBgNVBAYTAlVBMREwDwYDVQQHDAjQmtC40ZfQsgIUM7bLe/chuc4EAAAAfcMhAElhTwAwggQHBgsqhkiG9w0BCRACFDGCA/YwggPyBgkqhkiG9w0BBwKgggPjMIID3wIBAzEOMAwGCiqGJAIBAQEBAgEwawYLKoZIhvcNAQkQAQSgXARaMFgCAQEGCiqGJAIBAQECAwEwMDAMBgoqhiQCAQEBAQIBBCDpgbKRfaVE4iGCyt1KHFLCKvx3KPsGE/Ojpyz35FpwCAIEA2i+JBgPMjAxNzA5MDcwODM2NDZaMYIDWzCCA1cCAQEwggETMIH6MT8wPQYDVQQKDDbQnNGW0L3RltGB0YLQtdGA0YHRgtCy0L4g0Y7RgdGC0LjRhtGW0Zcg0KPQutGA0LDRl9C90LgxMTAvBgNVBAsMKNCQ0LTQvNGW0L3RltGB0YLRgNCw0YLQvtGAINCG0KLQoSDQptCX0J4xSTBHBgNVBAMMQNCm0LXQvdGC0YDQsNC70YzQvdC40Lkg0LfQsNGB0LLRltC00YfRg9Cy0LDQu9GM0L3QuNC5INC+0YDQs9Cw0L0xGTAXBgNVBAUMEFVBLTAwMDE1NjIyLTIwMTIxCzAJBgNVBAYTAlVBMREwDwYDVQQHDAjQmtC40ZfQsgIUMAR1He8seK4CAAAAAQAAAE4AAAAwDAYKKoYkAgEBAQECAaCCAdowGgYJKoZIhvcNAQkDMQ0GCyqGSIb3DQEJEAEEMBwGCSqGSIb3DQEJBTEPFw0xNzA5MDcwODM2NDZaMC8GCSqGSIb3DQEJBDEiBCCphPfwAkRgVFV+BMC1V6oFI+ERZ6mB6O2ZMmHaHrUGeDCCAWsGCyqGSIb3DQEJEAIvMYIBWjCCAVYwggFSMIIBTjAMBgoqhiQCAQEBAQIBBCCXESALiFxAOupDwKG7RVcxyB2LTq6aaPq+0pyjP6HWATCCARowggEApIH9MIH6MT8wPQYDVQQKDDbQnNGW0L3RltGB0YLQtdGA0YHRgtCy0L4g0Y7RgdGC0LjRhtGW0Zcg0KPQutGA0LDRl9C90LgxMTAvBgNVBAsMKNCQ0LTQvNGW0L3RltGB0YLRgNCw0YLQvtGAINCG0KLQoSDQptCX0J4xSTBHBgNVBAMMQNCm0LXQvdGC0YDQsNC70YzQvdC40Lkg0LfQsNGB0LLRltC00YfRg9Cy0LDQu9GM0L3QuNC5INC+0YDQs9Cw0L0xGTAXBgNVBAUMEFVBLTAwMDE1NjIyLTIwMTIxCzAJBgNVBAYTAlVBMREwDwYDVQQHDAjQmtC40ZfQsgIUMAR1He8seK4CAAAAAQAAAE4AAAAwDQYLKoYkAgEBAQEDAQEEQLUXNmCxeI6QSpw8rPqH703GBZZHGBDQqTJ/0dnr+fEAYDsLxET/VARYLhM6G9AkeQicW/THJu0CK/5yZ2gLzQIwDQYLKoYkAgEBAQEDAQEEQBdXFqZX8z90Gwhd42ZrxVaLIvbAdCd2+1pG+ukam2ItIzghlsVz5gZP+LXMaUK3uu7Vsn1/o7VUpu1quiK6mGw=",
  "signed_content_encoding":"base64"
}
```

## Response
```
{
    "meta": {
        "url": "http://192.168.99.100:30412/api/legal_entities",
        "type": "object",
        "request_id": "jqsa1qs8f6o8c0t4utnqaergc55tbr7t",
        "code": 500
    },
    "error": {
        "type": "internal_error"
    }
}
```

**Comment by AlexKovalevych** [comment]
```erlang
{"timestamp":"2017-09-12T13:48:09.505Z","sourceLocation":{"line":null,"function":null,"file":null},"severity":"ERROR","metadata":{"error_logger":"format"},"jsonPayload":{"serviceContext":{"version":null,"service":null},"message":"#PID<0.2319.0> running EHealth.Web.Endpoint terminated\nServer: dev.ehealth.world:80 (http)\nRequest: POST /api/employee_requests\n** (exit) an exception was raised:\n    ** (ErlangError) Erlang error: :if_clause\n        (stdlib) calendar.erl:117: :calendar.date_to_gregorian_days/3\n        (stdlib) calendar.erl:138: :calendar.datetime_to_gregorian_seconds/1\n        (timex) lib/datetime/naivedatetime.ex:25: Timex.Protocol.NaiveDateTime.to_gregorian_microseconds/1\n        (timex) lib/comparable/diff.ex:19: Timex.Comparable.Diff.diff/3\n        (timex) lib/comparable/naivedatetime.ex:15: Timex.Comparable.NaiveDateTime.compare/3\n        (ehealth) lib/ehealth/validators/birth_date.ex:16: EHealth.Validators.BirthDate.date_not_in_future/1\n        (ehealth) lib/ehealth/validators/birth_date.ex:8: EHealth.Validators.BirthDate.validate/1\n        (ehealth) lib/ehealth/employee/validator.ex:84: EHealth.Employee.Validator.validate_birth_date/1"}}
```
