### ISSUE TITLE
Deduplication service error

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#1987]
Deduplication service error

```
=SUPERVISOR REPORT==== 21-Mar-2018::13:16:01 ===
     Supervisor: {local,'Elixir.EHealth.DuplicatePersons.CleanupTasks'}
     Context:    child_terminated
     Reason:     {{badmatch,
                      {error,
                          #{<<"error">> =>
                                #{<<"errors">> =>
                                      #{<<"detail">> =>
                                            <<"Internal server error">>}},
                            <<"meta">> =>
                                #{<<"code">> => 500,
                                  <<"request_id">> =>
                                      <<"qqn8fs7b8bl8g6slcvko2h07vchit14q">>,
                                  <<"type">> => <<"object">>,
                                  <<"url">> =>
                                      <<"http://api-svc.mpi/merge_candidates/81bd7fbd-fad1-4f02-b699-db46b770827b">>}}}},
                  [{'Elixir.EHealth.DuplicatePersons.Cleanup',cleanup,2,
                       [{file,"lib/ehealth/duplicate_persons/cleanup.ex"},
                        {line,22}]},
                   {'Elixir.Enum','-each/2-lists^foreach/1-0-',2,
                       [{file,"lib/enum.ex"},{line,675}]},
                   {'Elixir.Enum',each,2,[{file,"lib/enum.ex"},{line,675}]},
                   {'Elixir.Task.Supervised',do_apply,2,
                       [{file,"lib/task/supervised.ex"},{line,85}]},
                   {proc_lib,init_p_do_apply,3,
                       [{file,"proc_lib.erl"},{line,247}]}]}
     Offender:   [{pid,<0.2340.0>},
                  {id,'Elixir.Task.Supervised'},
                  {mfargs,{'Elixir.Task.Supervised',start_link,undefined}},
                  {restart_type,temporary},
                  {shutdown,5000},
                  {child_type,worker}]


=SUPERVISOR REPORT==== 21-Mar-2018::13:16:01 ===
     Supervisor: {local,'Elixir.EHealth.DuplicatePersons.CleanupTasks'}
     Context:    child_terminated
     Reason:     {{badmatch,
                      {error,
                          #{<<"error">> =>
                                #{<<"errors">> =>
                                      #{<<"detail">> =>
                                            <<"Internal server error">>}},
                            <<"meta">> =>
                                #{<<"code">> => 500,
                                  <<"request_id">> =>
                                      <<"sbelssmmmfv4c3iha79vgpl8b10kpdpf">>,
                                  <<"type">> => <<"object">>,
                                  <<"url">> =>
                                      <<"http://api-svc.mpi/merge_candidates/8ff083ae-4cd7-4a3d-a2d0-d5ab5086c667">>}}}},
                  [{'Elixir.EHealth.DuplicatePersons.Cleanup',cleanup,2,
                       [{file,"lib/ehealth/duplicate_persons/cleanup.ex"},
                        {line,22}]},
                   {'Elixir.Enum','-each/2-lists^foreach/1-0-',2,
                       [{file,"lib/enum.ex"},{line,675}]},
                   {'Elixir.Enum',each,2,[{file,"lib/enum.ex"},{line,675}]},
                   {'Elixir.Task.Supervised',do_apply,2,
                       [{file,"lib/task/supervised.ex"},{line,85}]},
                   {proc_lib,init_p_do_apply,3,
                       [{file,"proc_lib.erl"},{line,247}]}]}
     Offender:   [{pid,<0.2326.0>},
                  {id,'Elixir.Task.Supervised'},
                  {mfargs,{'Elixir.Task.Supervised',start_link,undefined}},
                  {restart_type,temporary},
                  {shutdown,5000},
                  {child_type,worker}]

Task #PID<0.2317.0> started from EHealth.DuplicatePersons.Signals terminating
** (MatchError) no match of right hand side value: {:error, %{"error" => %{"errors" => %{"detail" => "Internal server error"}}, "meta" => %{"code" => 500, "request_id" => "hagtgjd92dmh60tshh8onuaq062n00ju", "type" => "object", "url" => "http://api-svc.mpi/merge_candidates/3bcbf456-ffb1-48c6-a6e4-acd6dd305eea"}}}
    (ehealth) lib/ehealth/duplicate_persons/cleanup.ex:22: EHealth.DuplicatePersons.Cleanup.cleanup/2
    (elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:675: Enum.each/2
    (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<4.71368659/0 in EHealth.DuplicatePersons.Signals.handle_call/3>
    Args: []
```

**Comment by lymychp** [comment]
not actual anymore
