### ISSUE TITLE
Problem on MPI

### ISSUE THREAD

**Issue by gmile** [edenlabllc/ehealth.api#2059]
From logs:
```
** (Postgrex.Error) ERROR 22P02 (invalid_text_representation): invalid input syntax for type json

Escape sequence "\1" is invalid.
    (ecto) lib/ecto/adapters/sql.ex:431: Ecto.Adapters.SQL.execute_and_cache/7
    (ecto) lib/ecto/repo/queryable.ex:133: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
    (ecto) lib/ecto/repo/queryable.ex:70: Ecto.Repo.Queryable.one/4
    (scrivener_ecto) lib/scrivener/paginater/ecto/query.ex:37: Scrivener.Paginater.Ecto.Query.total_entries/3
    (scrivener_ecto) lib/scrivener/paginater/ecto/query.ex:10: Scrivener.Paginater.Ecto.Query.paginate/2
    (mpi) lib/mpi/web/controllers/person_controller.ex:17: MPI.Web.PersonController.index/2
    (mpi) lib/mpi/web/controllers/person_controller.ex:1: MPI.Web.PersonController.action/2
```

**Comment by lymychp** [comment]
delivered to prod
