### ISSUE TITLE
Problem on AEL

### ISSUE THREAD

**Issue by gmile** [edenlabllc/ehealth.api#2069]
From logs:
```
** (CaseClauseError) no case clause matching: []
    (hackney) /app/deps/hackney/src/hackney_url.erl:192: :hackney_url.parse_netloc/2
    (hackney) /app/deps/hackney/src/hackney.erl:331: :hackney.request/5
    (httpoison) lib/httpoison/base.ex:439: HTTPoison.Base.request/9
    (ael_api) lib/ael_api/api/signature.ex:6: Ael.API.Signature.request!/5
    (ael_api) lib/ael_api/api/signature.ex:20: Ael.API.Signature.decode_and_validate/2
    (ael_api) lib/ael_api/secrets/api.ex:144: Ael.Secrets.API.validate_entity/1
    (ael_api) lib/ael_api/web/controllers/secret_controller.ex:22: Ael.Web.SecretController.validate/2
    (ael_api) lib/ael_api/web/controllers/secret_controller.ex:1: Ael.Web.SecretController.action/2
```

Retrieved using:

```
gcloud logging read 'insertId="1yrceong26yv111"' --format json --project ehealth-production
```

**Comment by gmile** [comment]
More info:

```json
{
  "api_version": "N/A",
  "client_ip": "N/A",
  "client_version": "hackney/1.8.6",
  "date_time": "2018-04-03T14:13:50Z",
  "duration": 491.436,
  "handler": "Elixir.Ael.Web.SecretController#validate",
  "log_type": "http",
  "method": "POST",
  "params": {
    "rules": [
      {
        "field": [
          "legal_entity",
          "edrpou"
        ],
        "type": "eq",
        "value": "38960408"
      },
      {
        "field": [
          "seed"
        ],
        "type": "eq",
        "value": "\\x9970c86762212151cb0c609e9f96004ca2365d21cd602ec5cf0c421360868293c54d452b48f8793d0c428704b4b1bd9314cd3b7f822ddeac1a883b81df3c18cb"
      }
    ],
    "url": "https://storage.googleapis.com/declarations/6c41307c-9e50-44a3-9cba-401c8ba4d064/signed_content?GoogleAccessId=ael-gcs@ehealth-production.iam.gserviceaccount.com&Expires=1522772029&Signature=b%2BOeTW3jUygCA4C1gRctrboRy%2FcyN3Rg598ONH3U50jvGUadnQBwNEzoTRN5OUTsBeej6ObiO48TaUIR%2FgyCczHYq1DbGl%2BEzJjuQ%2Bfd7nRwPGPHDNiXOv9QPGj5W8J15opELT%2BHrQ9bmz1lB%2BnnaaG0WZ9CvYG9zzx%2BiiDiNgnZaYigOWy4oSnkAK4d8hMm5z4rO5s9suhCWQs7Zs9TMyWcpXEucSC2uSkGOethVV6MouV9T9Eum68hO4MmrOvEzlDTkZxkIwIDqOSENzyjTgD3WnyxDGishg06Qj"
  },
  "path": "/validate_signed_entity",
  "request_id": "0pfh1d0lnouce9bfgn8b33vtia66o649",
  "status": 500
}
```

**Comment by gmile** [comment]
Closing, this was fixed by updating charts, see PR above.
