### ISSUE TITLE
Network DNS issues

### ISSUE THREAD

**Issue by gmile** [edenlabllc/ehealth.api#2087]
Full logs can be obtained via:

```
gcloud logging read 'jsonPayload.request_id="48e69a6e-181e-470b-ba5f-068a5b25c9da#34018"' --format json --project ehealth-production
```

Stacktrace from logs:
```
** (HTTPoison.Error) :nxdomain
    (ehealth) lib/ehealth/api/uaddress.ex:6: EHealth.API.UAddress."request! (overridable 1)"/5
    (ehealth) lib/ehealth/api/uaddress.ex:9: EHealth.API.UAddress.request!/5
    (ehealth) lib/ehealth/validators/addresses.ex:43: EHealth.Validators.Addresses.validate_address_values/2
    (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ehealth) lib/ehealth/validators/addresses.ex:34: EHealth.Validators.Addresses.validate_addresses_values/1
    (ehealth) lib/ehealth/declaration_requests/declaration_requests.ex:141: EHealth.DeclarationRequests.create_offline/2
    (ehealth) lib/ehealth/web/controllers/declaration_request_controller.ex:30: EHealth.Web.DeclarationRequestController.create/2
    (ehealth) lib/ehealth/web/controllers/declaration_request_controller.ex:1: EHealth.Web.DeclarationRequestController.action/2
```

The error is recurring:

<details>
<summary>Query</summary>

```
gcloud logging read 'jsonPayload.message:"(ehealth) lib/ehealth/api/uaddress.ex:6: EHealth.API.UAddress"' --format json --project ehealth-production | jq '. | map({timestamp: .timestamp, request_id: .jsonPayload.request_id})' | jq '(.[0] | keys_unsorted) as $keys | $keys, map([.[ $keys[] ]])[] | @csv' --raw-output | xsv table
```

</details>

```
timestamp             request_id
2018-04-05T04:51:10Z  d310bc65-0a45-47e1-81f8-5918e3c126aa#15881
2018-04-05T04:51:07Z  054aed58-374c-46d7-8a98-40475ff9fc08#3267
2018-04-05T04:46:19Z  8ab55903-7709-4ddb-9858-8ebc0ce33253#143752
2018-04-04T17:37:57Z  cb5b2e0d-65fa-4e5b-8072-6cbf231934be#189583
2018-04-04T14:48:58Z  8ab55903-7709-4ddb-9858-8ebc0ce33253#120830
2018-04-04T13:21:24Z  c07486c2-a437-4f96-a8ec-85115161b39c#262627
2018-04-04T11:48:05Z  6e21bb0c-6d15-4930-a943-a67825a94dad#2470
2018-04-04T06:40:15Z  f5fadb8e-d2fb-479e-988a-7c5f9bc54b87#4537
2018-04-04T06:40:15Z  48e69a6e-181e-470b-ba5f-068a5b25c9da#35593
2018-04-04T06:40:15Z  cb5b2e0d-65fa-4e5b-8072-6cbf231934be#29439
2018-04-04T06:40:14Z  48e69a6e-181e-470b-ba5f-068a5b25c9da#35614
2018-04-04T06:40:08Z  cb5b2e0d-65fa-4e5b-8072-6cbf231934be#29421
2018-04-04T06:40:08Z  4033922b-1356-4e0f-a4a4-df72cc6ba7af#31924
2018-04-04T06:40:08Z  6beac2fa-c5a4-4b6c-9a9a-0887368c6979#26363
2018-04-04T06:40:05Z  6beac2fa-c5a4-4b6c-9a9a-0887368c6979#26466
2018-04-04T06:40:05Z  4033922b-1356-4e0f-a4a4-df72cc6ba7af#31929
2018-04-04T06:36:24Z  cb5b2e0d-65fa-4e5b-8072-6cbf231934be#26575
2018-04-04T06:36:02Z  f5fadb8e-d2fb-479e-988a-7c5f9bc54b87#3704
2018-04-04T06:32:43Z  b5c8864f-2a8e-4479-9970-7c433f5e36be#3080
2018-04-04T06:32:43Z  fd372544-55d5-4b5c-994f-fdaf6b420c21#15380
2018-04-04T06:32:43Z  ce9c4929-aaed-43a5-a8dd-432f5a6789cb#94869
2018-04-04T06:32:11Z  48e69a6e-181e-470b-ba5f-068a5b25c9da#34037
2018-04-04T06:32:11Z  48e69a6e-181e-470b-ba5f-068a5b25c9da#34061
2018-04-04T06:32:02Z  cb5b2e0d-65fa-4e5b-8072-6cbf231934be#25468
2018-04-04T06:32:01Z  48e69a6e-181e-470b-ba5f-068a5b25c9da#34018
2018-04-04T06:32:01Z  cb5b2e0d-65fa-4e5b-8072-6cbf231934be#25455
2018-04-04T06:32:00Z  ce9c4929-aaed-43a5-a8dd-432f5a6789cb#94753
2018-04-04T06:32:00Z  f5fadb8e-d2fb-479e-988a-7c5f9bc54b87#2155
```

**Comment by gmile** [comment]
More evidence from @vsirius 
```E0405 06:02:56.575448       1 reflector.go:304] k8s.io/dns/pkg/dns/dns.go:150: Failed to watch *v1.Service: Get https://10.3.240.1:443/api/v1/services?resourceVersion=47820361&timeoutSeconds=577&watch=true: dial tcp 10.3.240.1:443: getsockopt: connection refused
E0405 06:02:56.575490       1 reflector.go:304] k8s.io/dns/pkg/dns/dns.go:147: Failed to watch *v1.Endpoints: Get https://10.3.240.1:443/api/v1/endpoints?resourceVersion=47997705&timeoutSeconds=515&watch=true: dial tcp 10.3.240.1:443: getsockopt: connection refused
E0405 06:02:57.619510       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:150: Failed to list *v1.Service: Get https://10.3.240.1:443/api/v1/services?resourceVersion=0: dial tcp 10.3.240.1:443: getsockopt: connection refused
E0405 06:02:58.621690       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:147: Failed to list *v1.Endpoints: Get https://10.3.240.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.3.240.1:443: getsockopt: connection refused
E0405 06:02:58.621921       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:150: Failed to list *v1.Service: Get https://10.3.240.1:443/api/v1/services?resourceVersion=0: dial tcp 10.3.240.1:443: getsockopt: connection refused```:

**Comment by gmile** [comment]
Possible solutions off the top to the head (via @lymychp):

- add more DNS nodes,
- give more resources to existing DNS nodes.

**Comment by gmile** [comment]
@vsirius what is this 10.3.240.1:443? API server? We don't have control over that. Why would it refuse connections?

**Comment by gmile** [comment]
Similar issues:

- [kube proxy issue with connection issue on master node
](https://stackoverflow.com/questions/47579870/kube-proxy-issue-with-connection-issue-on-master-node)
- [\[Error\] Getsockopt: connection refused - Kubernetes apiserver](https://github.com/kubernetes/contrib/issues/2249)
- [Problems accessing the API server](https://github.com/kubernetes/kubernetes/issues/31845)

Overall I'm starting to think the issue is related to DNS not being able to communicate to API server, sometimes. The question is – why? Heavy network traffic?

**Comment by lymychp** [comment]
fresh cases:
1) 
```
    "phoenix": {
      "status": 500,
      "request_id": "0396dbb0-b8b3-4868-ae7f-1eaa43cb0e0b#4042",
      "path": "/api/declaration_requests",
      "method": "POST",
      "log_type": "http",
      "handler": "Elixir.EHealth.Web.DeclarationRequestController#create",
      "duration": 166.648,
      "date_time": "2018-04-11T05:23:26Z",
      "api_version": "N/A"
    },
    "@timestamp": "2018-04-11T05:23:26.904103139+00:00",
    "tag": "phoenix.app"
```
2) 
```
    "phoenix": {
      "status": 500,
      "request_id": "d9760468-b7ec-4252-aeaf-561ebb659256#63278",
      "path": "/api/declaration_requests/0a37854c-d8bc-43f9-8b61-5e3c1dc40b1e/actions/sign",
      "method": "PATCH",
      "log_type": "http",
      "handler": "Elixir.EHealth.Web.DeclarationRequestController#sign",
      "duration": 50.928,
      "date_time": "2018-04-11T05:23:16Z",
      "api_version": "N/A"
    },
```

**Comment by vsirius** [comment]
I checked kubernetes system logs for last 2 weeks  and did not find any evidence, that this case could be reproduced in denovo production environment.   
All network kubernetes services ara working correctly.
