### ISSUE TITLE
Problem on OPS

### ISSUE THREAD

**Issue by gmile** [edenlabllc/ehealth.api#2089]
Obtained via:
```
gcloud logging read 'jsonPayload.request_id="1d5a244a-c288-4922-857f-79d4d3f44547#19040"' --format json --project ehealth-production
```

From logs:

```
** (Ecto.ConstraintError) constraint error when attempting to insert struct:

    * unique: declarations_pkey

If you would like to convert this constraint into an error, please
call unique_constraint/3 in your changeset and define the proper
constraint name. The changeset has not defined any constraint.

    (ecto) lib/ecto/repo/schema.ex:574: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3
    (elixir) lib/enum.ex:1270: Enum."-map/2-lists^map/1-0-"/2
    (ecto) lib/ecto/repo/schema.ex:559: Ecto.Repo.Schema.constraints_to_errors/3
    (ecto) lib/ecto/repo/schema.ex:222: anonymous fn/14 in Ecto.Repo.Schema.do_insert/4
    (ecto) lib/ecto/multi.ex:421: Ecto.Multi.apply_operation/5
    (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/multi.ex:411: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto) lib/ecto/adapters/sql.ex:576: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
```

**Comment by gmile** [comment]
Occurs from time to time, not severe:

```
timestamp             request_id
2018-04-05T05:42:07Z  1d5a244a-c288-4922-857f-79d4d3f44547#19040
2018-04-04T15:18:10Z  f62dfece-b813-4d8a-8f79-42259d720ebc#158897
2018-04-04T15:17:55Z  f62dfece-b813-4d8a-8f79-42259d720ebc#158854
2018-04-04T13:57:49Z  c07486c2-a437-4f96-a8ec-85115161b39c#272347
2018-04-04T13:57:14Z  6e21bb0c-6d15-4930-a943-a67825a94dad#32892
2018-04-04T13:56:32Z  6e21bb0c-6d15-4930-a943-a67825a94dad#32802
2018-04-04T13:55:48Z  f62dfece-b813-4d8a-8f79-42259d720ebc#147967
2018-04-04T13:55:41Z  12baf03c-00aa-4cdc-8d96-674fd0f4050c#136671
2018-04-04T13:55:26Z  11c21e0e-339a-4c8b-912e-79e6e9e1a0f8#47728
2018-04-04T13:55:18Z  1794eb91-10b6-459c-b20d-629a94e644f4#19503
2018-04-04T12:20:12Z  12e2b234-c05e-4f80-9451-ba84dd4d4e49#3018
2018-04-04T11:02:19Z  eeffdf5c-a741-459f-ad0a-45ebc0f30847#121648
2018-04-04T11:01:36Z  47df928b-7081-4194-8a0c-8dcdf69605d7#31792
2018-04-04T11:01:18Z  c07486c2-a437-4f96-a8ec-85115161b39c#221711
2018-04-04T11:01:02Z  cb5b2e0d-65fa-4e5b-8072-6cbf231934be#114345
2018-04-04T11:00:46Z  90c6f491-80d9-408c-a5b7-442a80da7f4f#42458
2018-04-04T11:00:41Z  8ab55903-7709-4ddb-9858-8ebc0ce33253#59003
2018-04-04T09:11:28Z  cb5b2e0d-65fa-4e5b-8072-6cbf231934be#81365
2018-04-04T09:11:28Z  8ab55903-7709-4ddb-9858-8ebc0ce33253#26092
2018-04-04T08:08:26Z  c07486c2-a437-4f96-a8ec-85115161b39c#166080
```

**Comment by lymychp** [comment]
delivered to prod
