### ISSUE TITLE
Error 500 /api/user/roles 

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#2522]
prod
```
"phoenix": {
      "request_id": "53ff408c-5b7b-4c4d-9a58-bab1d42294a5#61656",
      "message": "** (Protocol.UndefinedError) protocol String.Chars not implemented for %{\"0\" => \"bf6201dc-a979-449f-8563-79717aa13db9\", \"1\" => \"bf6201dc-a979-449f-8563-79717aa13db9\"}. This protocol is implemented for: Atom, BitString, Date, DateTime, Decimal, Ecto.Date, Ecto.DateTime, Ecto.Time, Float, Geo.GeometryCollection, Geo.LineString, Geo.MultiLineString, Geo.MultiPoint, Geo.MultiPolygon, Geo.Point, Geo.PointM, Geo.PointZ, Geo.PointZM, Geo.Polygon, Integer, List, NaiveDateTime, Postgrex.Copy, Postgrex.Query, Postgrex.Stream, Time, URI, Version, Version.Requirement\n    (elixir) /home/buildozer/aports/community/elixir/src/elixir-1.5.2/lib/elixir/lib/string/chars.ex:3: String.Chars.impl_for!/1\n    (elixir) /home/buildozer/aports/community/elixir/src/elixir-1.5.2/lib/elixir/lib/string/chars.ex:22: String.Chars.to_string/1\n    (elixir) lib/uri.ex:105: URI.encode_kv_pair/1\n    (elixir) lib/enum.ex:1340: anonymous fn/4 in Enum.map_join/3\n    (stdlib) lists.erl:1263: :lists.foldl/3\n    (elixir) lib/enum.ex:1843: Enum.map_join/3\n    (ehealth) lib/ehealth/api/mithril.ex:9: EHealth.API.Mithril.request/5\n    (ehealth) lib/ehealth/api/mithril.ex:7: EHealth.API.Mithril.\"request! (overridable 1)\"/5\n",
      "log_type": "error"
    },
    "@timestamp": "2018-06-25T05:05:32.773585826+00:00",
    "tag": "phoenix.error"
```

**Comment by AlexKovalevych** [comment]
`    "path": "/user/roles?client_id%5B0%5D=bf6201dc-a979-449f-8563-79717aa13db9&client_id%5B1%5D=bf6201dc-a979-449f-8563-79717aa13db9",`
