### ISSUE TITLE
HTTP poison Error 500 /api/declarations

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#2523]
It looks like we have 500 when client sends the same parameter twice. For example, `legal_entity_id`

`http://api-svc.ops/declarations?employee_id=154e8cc0-1a37-42e9-9190-adde45b8d850&is_active=true&legal_entity_id=423276a7-ef42-463b-83a8-3ff5569977a6&legal_enyity_id=423276a7-ef42-463b-83a8-3ff5569977a6&page=8&page_size=50&status=active`
```
"phoenix": {
      "request_id": "f6a73536-682d-4ece-b70f-430a14bd6c62#132230",
      "message": "** (HTTPoison.Error) :closed\n    (ehealth) lib/ehealth/api/ops.ex:6: EHealth.API.OPS.\"request! (overridable 1)\"/5\n    (ehealth) lib/ehealth/api/ops.ex:8: EHealth.API.OPS.request!/5\n    (ehealth) lib/ehealth/declarations/api.ex:20: EHealth.Declarations.API.get_declarations/2\n    (ehealth) lib/ehealth/web/controllers/declarations_controller.ex:11: EHealth.Web.DeclarationsController.index/2\n    (ehealth) lib/ehealth/web/controllers/declarations_controller.ex:1: EHealth.Web.DeclarationsController.action/2\n    (ehealth) lib/ehealth/web/controllers/declarations_controller.ex:1: EHealth.Web.DeclarationsController.phoenix_controller_pipeline/2\n    (ehealth) lib/ehealth/endpoint.ex:1: EHealth.Web.Endpoint.instrument/4\n    (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1\n",
      "log_type": "error"
    },
    "@timestamp": "2018-06-25T08:21:54.274495411+00:00",
    "tag": "phoenix.error"
```

**Comment by lymychp** [comment]
get `/api/persons/
```
  "phoenix": {
      "request_id": "a0fd57d3-c6d1-498c-bdcd-289c36cc9dca#6396",
      "message": "** (HTTPoison.Error) :closed\n    (ehealth) lib/ehealth/api/mpi.ex:6: EHealth.API.MPI.\"request! (overridable 1)\"/5\n    (ehealth) lib/ehealth/api/mpi.ex:8: EHealth.API.MPI.request!/5\n    (ehealth) lib/ehealth/persons/persons.ex:17: EHealth.Persons.search/2\n    (ehealth) lib/ehealth/web/controllers/person_controller.ex:18: EHealth.Web.PersonController.search_persons/2\n    (ehealth) lib/ehealth/web/controllers/person_controller.ex:1: EHealth.Web.PersonController.action/2\n    (ehealth) lib/ehealth/web/controllers/person_controller.ex:1: EHealth.Web.PersonController.phoenix_controller_pipeline/2\n    (ehealth) lib/ehealth/endpoint.ex:1: EHealth.Web.Endpoint.instrument/4\n    (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1\n",
      "log_type": "error"
    },
    "@timestamp": "2018-06-26T08:17:23.252615060+00:00",
    "tag": "phoenix.error"
  },
```

**Comment by lymychp** [comment]
still reproducible
```
    "phoenix": {
      "status": 500,
      "request_id": "c08a167b-297b-4b2e-8a32-4d16a424691a#442815",
      "path": "/api/declaration_requests/0934828d-042d-4339-8649-f12ea9943b08/actions/sign",
      "method": "PATCH",
      "log_type": "http",
      "handler": "Elixir.EHealth.Web.DeclarationRequestController#sign",
      "duration": 27.125,
      "date_time": "2018-08-15T06:39:49Z",
      "api_version": "N/A"
    },
    "@timestamp": "2018-08-15T06:39:49.377177800+00:00",
    "tag": "phoenix.app"
  },
```

**Comment by lymychp** [comment]
```
   "phoenix": {
      "request_id": "184ce254-f7a5-46a9-8480-4248f884e4f0#18554",
      "message": "** (HTTPoison.Error) :closed\n    (ehealth) lib/ehealth/api/mpi.ex:6: EHealth.API.MPI.\"request! (overridable 1)\"/5\n    (ehealth) lib/ehealth/api/mpi.ex:6: EHealth.API.MPI.request!/5\n    (ehealth) lib/ehealth/declaration_requests/api/sign.ex:186: EHealth.DeclarationRequests.API.Sign.create_or_update_person/3\n    (ehealth) lib/ehealth/declaration_requests/api/sign.ex:38: EHealth.DeclarationRequests.API.Sign.sign/2\n    (ehealth) lib/ehealth/web/controllers/declaration_request_controller.ex:79: EHealth.Web.DeclarationRequestController.sign/2\n    (ehealth) lib/ehealth/web/controllers/declaration_request_controller.ex:1: EHealth.Web.DeclarationRequestController.action/2\n    (ehealth) lib/ehealth/web/controllers/declaration_request_controller.ex:1: EHealth.Web.DeclarationRequestController.phoenix_controller_pipeline/2\n    (ehealth) lib/ehealth/endpoint.ex:1: EHealth.Web.Endpoint.instrument/4\n",
      "log_type": "error"
    },
    "@timestamp": "2018-08-17T04:28:00.428155831+00:00",
    "tag": "phoenix.error"
  },
```
