### ISSUE TITLE
DBConnection Error 500 /api/declarations

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#2660]
we have a number of new errors on prod.
Might be caused by the migrations/indexes.
```
 "phoenix": {
      "request_id": "697e5759-9799-4e34-9ca1-e0741b229e57#24686",
      "message": "** (DBConnection.ConnectionError) tcp recv: closed\n    (ecto) lib/ecto/adapters/postgres/connection.ex:108: Ecto.Adapters.Postgres.Connection.execute/4\n    (ecto) lib/ecto/adapters/sql.ex:256: Ecto.Adapters.SQL.sql_call/6\n    (ecto) lib/ecto/adapters/sql.ex:436: Ecto.Adapters.SQL.execute_or_reset/7\n    (ecto) lib/ecto/repo/queryable.ex:133: Ecto.Repo.Queryable.execute/5\n    (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4\n    (scrivener_ecto) lib/scrivener/paginater/ecto/query.ex:15: Scrivener.Paginater.Ecto.Query.paginate/2\n    (ops) lib/ops/web/controllers/declaration_controller.ex:13: OPS.Web.DeclarationController.index/2\n    (ops) lib/ops/web/controllers/declaration_controller.ex:1: OPS.Web.DeclarationController.action/2\n",
      "log_type": "error"
    },
```
@AlexKovalevych @vsirius

**Comment by lymychp** [comment]
declaration_requests as well
```
"phoenix": {
      "request_id": "572785af-6c41-450a-aa67-00fec59be9a0#77637",
      "message": "** (DBConnection.ConnectionError) tcp recv: closed\n    (ecto) lib/ecto/adapters/postgres/connection.ex:108: Ecto.Adapters.Postgres.Connection.execute/4\n    (ecto) lib/ecto/adapters/sql.ex:256: Ecto.Adapters.SQL.sql_call/6\n    (ecto) lib/ecto/adapters/sql.ex:436: Ecto.Adapters.SQL.execute_or_reset/7\n    (ecto) lib/ecto/repo/queryable.ex:133: Ecto.Repo.Queryable.execute/5\n    (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4\n    (ecto) lib/ecto/repo/queryable.ex:70: Ecto.Repo.Queryable.one/4\n    (scrivener_ecto) lib/scrivener/paginater/ecto/query.ex:37: Scrivener.Paginater.Ecto.Query.total_entries/3\n    (scrivener_ecto) lib/scrivener/paginater/ecto/query.ex:10: Scrivener.Paginater.Ecto.Query.paginate/2\n",
      "log_type": "error"
    },
    "@timestamp": "2018-07-16T08:19:12.836222583+00:00",
    "tag": "phoenix.error"
```

**Comment by lymychp** [comment]
this kind of error doesn't appear on prod anymore
