### ISSUE TITLE
[Man] Get templates error

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#2724]
### Man Web

```
curl 'http://localhost:8082/api/templates?limit=100' -H 'pragma: no-cache' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9,uk;q=0.8,ru;q=0.7' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36' -H 'content-type: application/json' -H 'Accept: */*' -H 'Referer: http://localhost:8082/templates' -H 'Connection: keep-alive' -H 'cache-control: no-cache' --compressed
```

```
{"request_id":"2l17nddrs6fpfsrc7403rnf1","message":"** (ArgumentError) cannot load embed `locales`, invalid value: nil\n    (ecto) lib/ecto/type.ex:472: Ecto.Type.load_embed/4\n    (elixir) lib/enum.ex:1270: Enum.\"-map/2-lists^map/1-0-\"/2\n    (ecto) lib/ecto/type.ex:460: Ecto.Type.load_embed/3\n    (ecto) lib/ecto/type.ex:659: Ecto.Type.process_loaders/3\n    (ecto) lib/ecto/schema.ex:1490: Ecto.Schema.load!/5\n    (ecto) lib/ecto/schema.ex:1442: Ecto.Schema.safe_load_zip/4\n    (ecto) lib/ecto/schema.ex:1443: Ecto.Schema.safe_load_zip/4\n    (ecto) lib/ecto/schema.ex:1430: Ecto.Schema.__safe_load__/6\n","log_type":"error"}
#PID<0.7149.8> running Man.Web.Endpoint terminated
Server: api-svc.man:80 (http)
Request: GET /templates?limit=100
** (exit) an exception was raised:
    ** (ArgumentError) cannot load embed `locales`, invalid value: nil
        (ecto) lib/ecto/type.ex:472: Ecto.Type.load_embed/4
        (elixir) lib/enum.ex:1270: Enum."-map/2-lists^map/1-0-"/2
        (ecto) lib/ecto/type.ex:460: Ecto.Type.load_embed/3
        (ecto) lib/ecto/type.ex:659: Ecto.Type.process_loaders/3
        (ecto) lib/ecto/schema.ex:1490: Ecto.Schema.load!/5
        (ecto) lib/ecto/schema.ex:1442: Ecto.Schema.safe_load_zip/4
        (ecto) lib/ecto/schema.ex:1443: Ecto.Schema.safe_load_zip/4
        (ecto) lib/ecto/schema.ex:1430: Ecto.Schema.__safe_load__/6
```

**Comment by AlekzandrV** [comment]
Fixed
