### ISSUE TITLE
Get contracts employees page size

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#2736]
if change page_size in get contract employees in response will be received 500 Error

Request
```
curl -X GET \
  'https://api.dev.asclepius.com.ua/api/contracts/40b40348-e387-4b4d-848b-f4d25c04d015/employees?page_size=100' \
  -H 'api-key: UXhEczJacXh3Ri9SUkc4enhHTVVpQT09' \
  -H 'authorization: Bearer blo1ZmtGMnp1enhWNm1MaWprY0xLZz09' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'drfo: 3067305998' \
  -H 'postman-token: 33bb5775-ce27-0319-899e-ee7b4d46013e' \
  -d '{"signed_content":"eyJlbXBsb3llZV9pZCI6IjJiYjZiNTQwLTJhYzctNGY4NC1iYjk2LThiYjM2YzEzNWIyNCIsImRpdmlzaW9uX2lkIjoiMjNmOWUyN2UtZDI5MC00NWFmLThlNzQtMzBkNmVmMzM1YmM5Iiwic3RhZmZfdW5pdHMiOjAuNSwiZGVjbGFyYXRpb25fbGltaXQiOjMwMDB9",
"signed_content_encoding": "base64"
}	'
```

Response
```
{"meta":{"url":"http://api-svc.il/api/contracts/40b40348-e387-4b4d-848b-f4d25c04d015/employees","type":"object","request_id":"e9520d7b-eaed-4698-a50b-580e3b4895e4#46070","code":500},"error":{"errors":{"detail":"Internal server error"}}}
```

**Comment by danakonovalenko** [comment]
child of GET CONTRACT EMPLOYEES with parameter page_size DEMO #2732

**Comment by AlexKovalevych** [comment]
```
{"request_id":"e9520d7b-eaed-4698-a50b-580e3b4895e4#46070","message":"** (Ecto.SubQueryError) the following exception happened when compiling a subquery.\n\n    ** (Ecto.QueryError) apps/ehealth/lib/ehealth/contracts/contracts.ex:413: field `page_size` in `where` does not exist in schema EHealth.Contracts.ContractEmployee in query:\n    \n    from c in EHealth.Contracts.ContractEmployee,\n      where: c.page_size == ^20,\n      where: c.contract_id == ^\"40b40348-e387-4b4d-848b-f4d25c04d015\",\n      where: is_nil(c.end_date) or c.end_date > ^~N[2018-07-18 22:42:40.951477]\n    \n\nThe subquery originated from the following query:\n\nfrom c in subquery(from c in EHealth.Contracts.ContractEmployee,\n  where: c.page_size == ^20,\n  where: c.contract_id == ^\"40b40348-e387-4b4d-848b-f4d25c04d015\",\n  where: is_nil(c.end_date) or c.end_date > ^~N[2018-07-18 22:42:40.951477]),\n  select: count(\"*\")\n\n    (ecto) lib/ecto/repo/queryable.ex:124: Ecto.Repo.Queryable.execute/5\n    (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4\n    (ecto) lib/ecto/repo/queryable.ex:70: Ecto.Repo.Queryable.one/4\n    (scrivener_ecto) lib/scrivener/paginater/ecto/query.ex:37: Scrivener.Paginater.Ecto.Query.total_entries/3\n","log_type":"error"}
```
