### ISSUE TITLE
ecto stale struct error 500 post /api/declaration_requests/ID/actions/sign

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#2807]
```
    "phoenix": {
      "request_id": "40330d91-0a47-48fe-ae9f-90e4f5f4ec3e#37372",
      "message": "** (Ecto.StaleEntryError) attempted to delete a stale struct:\n\n%MPI.PersonPhone{__meta__: #Ecto.Schema.Metadata<:loaded, \"person_phones\">, id: \"9f43875a-e410-4768-a0ea-881c697ba313\", inserted_at: #DateTime<2018-07-11 11:48:11.231913Z>, number: \"+380971371065\", person: #Ecto.Association.NotLoaded<association :person is not loaded>, person_id: \"356188d7-d433-4387-9304-b4c75ed2f46c\", type: \"MOBILE\", updated_at: #DateTime<2018-07-11 11:48:11.231924Z>}\n\n    (ecto) lib/ecto/repo/schema.ex:553: Ecto.Repo.Schema.apply/4\n    (ecto) lib/ecto/repo/schema.ex:379: anonymous fn/9 in Ecto.Repo.Schema.do_delete/4\n    (ecto) lib/ecto/association.ex:556: Ecto.Association.Has.on_repo_change/4\n    (ecto) lib/ecto/association.ex:542: Ecto.Association.Has.on_repo_change/4\n    (ecto) lib/ecto/association.ex:338: anonymous fn/7 in Ecto.Association.on_repo_change/6\n    (elixir) lib/enum.ex:1899: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n    (ecto) lib/ecto/association.ex:335: Ecto.Association.on_repo_change/6\n    (elixir) lib/enum.ex:1899: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n",
      "log_type": "error"
    },
    "@timestamp": "2018-07-25T11:12:16.508061978+00:00",
    "tag": "phoenix.error"
  },
```

**Comment by AlexKovalevych** [comment]
Two identical requests with interval of less than 100 milliseconds:

```
c1b34b63-71e0-4a06-9d74-7363b820a2f2#101767 - July 25th 2018, 14:12:16.593
40330d91-0a47-48fe-ae9f-90e4f5f4ec3e#37372 - July 25th 2018, 14:12:16.512
```

**Comment by lymychp** [comment]
can we respond not 500 in this case?

**Comment by AlexKovalevych** [comment]
in theory - yes, but that needs deep ecto library investigation

**Comment by lymychp** [comment]
for future considiration: to calculate hash of the request payload to eliminate request duplication from clients.
