### ISSUE TITLE
connection closed error 500 GET /api/declarations

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#2808]
```
  "phoenix": {
      "request_id": "4a320e35-b1cd-479e-a338-fe479173269c#47790",
      "message": "** (DBConnection.ConnectionError) tcp recv: closed\n    (ecto) lib/ecto/adapters/postgres/connection.ex:108: Ecto.Adapters.Postgres.Connection.execute/4\n    (ecto) lib/ecto/adapters/sql.ex:256: Ecto.Adapters.SQL.sql_call/6\n    (ecto) lib/ecto/adapters/sql.ex:436: Ecto.Adapters.SQL.execute_or_reset/7\n    (ecto) lib/ecto/repo/queryable.ex:133: Ecto.Repo.Queryable.execute/5\n    (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4\n    (scrivener_ecto) lib/scrivener/paginater/ecto/query.ex:15: Scrivener.Paginater.Ecto.Query.paginate/2\n    (ops) lib/ops/web/controllers/declaration_controller.ex:13: OPS.Web.DeclarationController.index/2\n    (ops) lib/ops/web/controllers/declaration_controller.ex:1: OPS.Web.DeclarationController.action/2\n",
      "log_type": "error"
    },
    "@timestamp": "2018-07-25T10:44:08.029929802+00:00",
    "tag": "phoenix.error"
  },
```

**Comment by lymychp** [comment]
>db closed connection during query processing

reason? solution? how to avoid this kind of problems in future?

**Comment by AlexKovalevych** [comment]
Reason - db backups
solution - discussable

**Comment by lymychp** [comment]
"@timestamp": "2018-07-25T10:44:08.029929802+00:00",
DB backups? @vsirius please confirm

**Comment by vsirius** [comment]
db log

2018-07-25 10:44:08.032 UTC [54550] [user: db] [database: ops] [host: 10.244.1.71] ERROR:  canceling statement due to user request

**Comment by lymychp** [comment]
should be fixed after ops optimization
