### ISSUE TITLE
no match of right hand side error 500 post /api/declaration_requests/../actions/sign

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#2827]
```
  "phoenix": {
      "request_id": "54d592fb-315c-4f75-9ce0-244543ed77a0#100012",
      "message": "** (MatchError) no match of right hand side value: {:error, {:empty_body, 408}}\n    (ehealth) lib/ehealth/declaration_requests/api/sign.ex:303: EHealth.DeclarationRequests.API.Sign.current_hash/1\n    (ehealth) lib/ehealth/declaration_requests/api/sign.ex:121: EHealth.DeclarationRequests.API.Sign.compare_with_db/3\n    (ehealth) lib/ehealth/declaration_requests/api/sign.ex:34: EHealth.DeclarationRequests.API.Sign.sign/2\n    (ehealth) lib/ehealth/web/controllers/declaration_request_controller.ex:79: EHealth.Web.DeclarationRequestController.sign/2\n    (ehealth) lib/ehealth/web/controllers/declaration_request_controller.ex:1: EHealth.Web.DeclarationRequestController.action/2\n    (ehealth) lib/ehealth/web/controllers/declaration_request_controller.ex:1: EHealth.Web.DeclarationRequestController.phoenix_controller_pipeline/2\n    (ehealth) lib/ehealth/endpoint.ex:1: EHealth.Web.Endpoint.instrument/4\n    (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1\n",
      "log_type": "error"
    },
    "@timestamp": "2018-07-26T06:07:21.483865456+00:00",
    "tag": "phoenix.error"
  },
```

**Comment by AlexKovalevych** [comment]
get latest block failed to complete (ops db issue?)

**Comment by lymychp** [comment]
let's monitor this kind of error further

**Comment by lymychp** [comment]
not relevant anymore
