### ISSUE TITLE
500 error POST /declaration_requests PROD (j156)

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2973]
MIS:
MEDSTAR
Середовище:
Prod
Steps to reproduce:
500 ошибка запросе POST /declaration_requests
Expected results:
200 или не 500 ошибка

Детали 
https://drive.google.com/drive/u/0/folders/1fv0rFWQkTB-yT1sRtwZLU_VK4BX0uv10

**Comment by svetavedmed** [comment]
```
** (Postgrex.Error) ERROR 25P02 (in_failed_sql_transaction): current transaction is aborted, commands ignored until end of transaction block
    (ecto) lib/ecto/adapters/sql.ex:440: Ecto.Adapters.SQL.execute_or_reset/7
    (ecto) lib/ecto/repo/queryable.ex:133: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
    (ehealth) lib/ehealth/dictionaries/dictionaries.ex:23: EHealth.Dictionaries.search_dictionaries/1
    (ehealth) lib/ehealth/dictionaries/dictionaries.ex:84: EHealth.Dictionaries.get_dictionary_value/2
    (elixir) lib/map.ex:736: Map.update!/3
    (ehealth) lib/ehealth/man/templates/declaration_request_printout_form.ex:111: EHealth.Man.Templates.DeclarationRequestPrintoutForm.get_document/3
    (ehealth) lib/ehealth/man/templates/declaration_request_printout_form.ex:62: EHealth.Man.Templates.DeclarationRequestPrintoutForm.get_person/1
```

**Comment by lymychp** [comment]
not relevant anymore.
In case of the same error in future it is recommended to retry.
