### ISSUE TITLE
empty_body error 500 GET /api/declaration_requests

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#3124]
```
    "phoenix": {
      "request_id": "92602b83-0d05-493b-bf7a-44b0da165b19#43793",
      "message": "** (MatchError) no match of right hand side value: {:error, {:empty_body, 408}}\n    (ehealth) lib/ehealth/web/controllers/declaration_request_controller.ex:25: EHealth.Web.DeclarationRequestController.show/2\n    (ehealth) lib/ehealth/web/controllers/declaration_request_controller.ex:1: EHealth.Web.DeclarationRequestController.action/2\n    (ehealth) lib/ehealth/web/controllers/declaration_request_controller.ex:1: EHealth.Web.DeclarationRequestController.phoenix_controller_pipeline/2\n    (ehealth) lib/ehealth/endpoint.ex:1: EHealth.Web.Endpoint.instrument/4\n    (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1\n    (ehealth) lib/plug/error_handler.ex:64: EHealthWeb.Router.call/2\n    (ehealth) lib/ehealth/endpoint.ex:1: EHealth.Web.Endpoint.plug_builder_call/2\n    (ehealth) lib/ehealth/endpoint.ex:1: EHealth.Web.Endpoint.call/2\n",
      "log_type": "error"
    },
    "@timestamp": "2018-09-17T04:18:34.176719559+00:00",
    "tag": "phoenix.error"
  },
```

**Comment by lymychp** [comment]
not relevant anymore
