### ISSUE TITLE
Enumerable not implemented error 500 GET /divisions

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#3167]
```
  "phoenix": {
      "request_id": "eeafffdf-6477-4443-9b5e-0b705c9d904c#224107",
      "message": "** (Protocol.UndefinedError) protocol Enumerable not implemented for #Ecto.Association.NotLoaded<association :addresses is not loaded>. This protocol is implemented for: DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Postgrex.Stream, Range, Scrivener.Page, Stream, Timex.Interval\n    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1\n    (elixir) lib/enum.ex:141: Enumerable.reduce/3\n    (elixir) lib/enum.ex:1911: Enum.map/2\n    (ehealth) lib/ehealth/web/views/division_view.ex:31: EHealth.Web.DivisionView.render/2\n    (elixir) lib/enum.ex:1294: Enum.\"-map/2-lists^map/1-0-\"/2\n    (phoenix) lib/phoenix/view.ex:332: Phoenix.View.render_to_iodata/3\n    (phoenix) lib/phoenix/controller.ex:740: Phoenix.Controller.do_render/4\n    (ehealth) lib/ehealth/web/controllers/division_controller.ex:1: EHealth.Web.DivisionController.action/2\n",
      "log_type": "error"
    },
    "@timestamp": "2018-09-24T13:44:04.732255938+00:00",
    "tag": "phoenix.error"
  },
```

**Comment by jeffhsta** [comment]
I wasn't able to test it, I think because of some missing plugin in Postgres, but it may fix the issue.

**Comment by AlekzandrV** [comment]
Tested with different scenarios. I can't reproduce this bug
