### ISSUE TITLE
Approve declaration request - Error 500

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#799]
Error 500 on Approve declaration request:

Request:
```
curl -X PATCH \
  http://dev.ehealth.world/api/declaration_requests/b9cfb6dd-1677-449b-b1a5-7304ca1a6b5e/actions/approve \
  -H 'authorization: Bearer UjRweUN4a2RKOWd5Ui9pV0xUNDkyUT09' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 5f7376ff-2b79-e380-ba49-311a89609318' \
  -d '{
  "verification_code": 7227
}'
```

Response:
```
{
    "meta": {
        "url": "http://dev.ehealth.world/api/declaration_requests/b9cfb6dd-1677-449b-b1a5-7304ca1a6b5e/actions/approve",
        "type": "object",
        "request_id": "ceaankg7nlvq3r9rfguk82lvg5cqutjb",
        "code": 500
    },
    "error": {
        "type": "internal_error"
    }
}
```

**Comment by PavelVesnin** [comment]
```
EHealth.Web.Endpoint terminated\nServer: dev.ehealth.world:80 (http)\nRequest: PATCH /api/declaration_requests/b9cfb6dd-1677-449b-b1a5-7304ca1a6b5e/actions/approve\n** (exit) an exception was raised:\n    ** (WithClauseError) no with clause matching: {:error, :verification, %{\"type\" => \"person.PASSPORT\", \"url\" => \"https://storage.googleapis.com/declaration-requests-dev/b9cfb6dd-1677-449b-b1a5-7304ca1a6b5e/declaration_request_person.PASSPORT.jpeg?GoogleAccessId=ael-dev@ehealth-162117.iam.gserviceaccount.com&Expires=1502201679&Signature=kCGj4icCDdYhFMLJUntrb3dm2aW9w%2FfBpb4G%2BO3EH%2F%2BqEipCa3tcERxTb%2FLdpVJ%2BAz%2F3D9M38nesBS9mVaokAFTil9w78ONccmwZN3UExE7nRvtJeuWJIkQYGPBJC11FhA8zd2h8v5r758yo9F%2BSil2w9KccpXzpC9QmXjinFMNu7LNVRhTG0XkEoCRZBtjxAtYMLxMvnLhZkcGGMM2vcaX%2FvsKP%2BfUt702QtPBDj5QUEOsya6VtcbnAnX2z%2B2cdrNnVlyLCkNDcce2JFuyWjmSPpmsigPGwPgQeMLaJO%2FpqwPnlrMMzh4LV02vHVyY9LCeKoAJmvOdYv4RvxnSb6w%3D%3D\", \"verb\" => \"PUT\"}, %{}}\n        (ehealth) lib/ehealth/web/controllers/declaration_request_controller.ex:38: EHealth.Web.DeclarationRequestController.approve/2\n        (ehealth) lib/ehealth/web/controllers/declaration_request_controller.ex:1: EHealth.Web.DeclarationRequestController.action/2\n        (ehealth) lib/ehealth/web/controllers/declaration_request_controller.ex:1: EHealth.Web.DeclarationRequestController.phoenix_controller_pipeline/2\n        (ehealth) lib/ehealth/web/endpoint.ex:1: EHealth.Web.Endpoint.instrument/4\n        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1\n        (ehealth) lib/ehealth/web/endpoint.ex:1: EHealth.Web.Endpoint.plug_builder_call/2\n        (ehealth) lib/ehealth/web/endpoint.ex:1: EHealth.Web.Endpoint.call/2\n        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4"
```
