### ISSUE TITLE
Sign declaration request with invalid base64 string

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#861]
I'm trying to sign declaration request with invalid base64 string
Got 500

# Steps to reproduce:
## Request:
Missed `\n` new line at the end of signed_content
[Sign_declaration_request_curl.txt](https://github.com/edenlabllc/ehealth.api/files/1224893/Sign_declaration_request_curl.txt)

## Response:
```
{
    "meta": {
        "url": "http://dev.ehealth.world/api/declaration_requests/37481ef1-8d3a-4b52-9641-35b7da8c3eb5/actions/sign",
        "type": "object",
        "request_id": "3gfjp6e1ajn6p109siv0s7tgoih9ejde",
        "code": 500
    },
    "error": {
        "type": "internal_error"
    }
}
```

**Comment by Troush** [comment]
```
{"timestamp":"2017-08-18T14:57:50.301Z","sourceLocation":{"line":null,"function":null,"file":null},"severity":"ERROR","metadata":{"error_logger":"format"},"jsonPayload":{"serviceContext":{"version":null,"service":null},"message":"#PID<0.1979.0> running EHealth.Web.Endpoint terminated\nServer: dev.ehealth.world:80 (http)\nRequest: PATCH /api/declaration_requests/6daf6538-3238-4478-875b-0aad2be86e84/actions/sign\n** (exit) an exception was raised:\n    ** (FunctionClauseError) no function clause matching in EHealth.DeclarationRequest.API.Validations.check_is_valid/1\n        (ehealth) lib/ehealth/declaration_request/api/validations.ex:162: EHealth.DeclarationRequest.API.Validations.check_is_valid({:error, %{\"error\" => %{\"invalid\" => [%{\"entry\" => \"$.signed_content\", \"entry_type\" => \"json_data_property\", \"rules\" => [%{\"description\" => \"not a base64 string\", \"params\" => [], \"rule\" => \"invalid\"}]}], \"message\" => \"Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.\", \"type\" => \"validation_failed\"}, \"meta\" => %{\"code\" => 422, \"request_id\" => \"0t6g76ik1n65l9ra011nemhiq8s9prn8\", \"type\" => \"object\", \"url\" => \"http://api-svc.digital-signature/digital_signatures\"}}})\n        (ehealth) lib/ehealth/declaration_request/api.ex:328: EHealth.DeclarationRequest.API.sign/2\n        (ehealth) lib/ehealth/web/controllers/declaration_request_controller.ex:58: EHealth.Web.DeclarationRequestController.sign/2\n        (ehealth) lib/ehealth/web/controllers/declaration_request_controller.ex:1: EHealth.Web.DeclarationRequestController.action/2\n        (ehealth) lib/ehealth/web/controllers/declaration_request_controller.ex:1: EHealth.Web.DeclarationRequestController.phoenix_controller_pipeline/2\n        (ehealth) lib/ehealth/web/endpoint.ex:1: EHealth.Web.Endpoint.instrument/4\n        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1\n        (ehealth) lib/ehealth/web/endpoint.ex:1: EHealth.Web.Endpoint.plug_builder_call/2"}}
```

**Comment by AlekzandrV** [comment]
Test - Failed:
```
{
    "meta": {
        "url": "http://dev.ehealth.world/api/declaration_requests/c9cbc99d-6973-4df0-bf71-adb0f17da119/actions/sign",
        "type": "object",
        "request_id": "9i9rbqkp80ivt5uanran0cf8o3gsbam8",
        "code": 501
    },
    "error": {
        "type": "internal_error"
    }
}
```

**Comment by lymychp** [comment]
@AlekzandrV still failed?

**Comment by svetavedmed** [comment]
try to sing two invalid base64 string
first try receive 422
request [error_422.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46ed86882c90bcfdddbbfd0fe64de29b234324676b5ee17e29d4e22cee472352595a1afa46585e47afad887af0b56d62964e49bc8f3900299f7744eeaa880dbe08b0218e4f82b0b88b4cc8e13b25e199c2.txt)
response
```
{
    "meta": {
        "url": "http://dev.ehealth.world/api/declaration_requests/d5e42b56-7ca9-4869-94c0-c6d9477a9826/actions/sign",
        "type": "object",
        "request_id": "k8g2091nvpjp9sdufpgf7ndhmkuj2jmh",
        "code": 422
    },
    "error": {
        "is_valid": false
    }
}
```
next try receive 500
request [error_500.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46ed86882c90bcfcdfb9fd0fe64de29b234324676b5ee17e29d4e22cee472352595a1afa46585e47afad887af0b56d62964e49bc8f3900299f7744eeaa880dbe06b0218e4f82b0b88b4dc3ef3424e499c2.txt)
response
```
{
    "meta": {
        "url": "http://dev.ehealth.world/api/declaration_requests/d5e42b56-7ca9-4869-94c0-c6d9477a9826/actions/sign",
        "type": "object",
        "request_id": "rechgprjan93jh30l95eoab3j1dcm5il",
        "code": 500
    },
    "error": {
        "type": "internal_error"
    }
}
```
according to [#1159](https://github.com/edenlabllc/ehealth.api/issues/1159) declaration are singed without real digital signature

**Comment by svetavedmed** [comment]
sometimes I still have 500
request [error-500.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46ed86882c90cefcdfb9fd0fe64de29b234324676b5ee17e29d4e22cee472352595a1afa46585e47afad887af0b56d62964e49bc8f3900299f7744eeaa880dbe09b0218e4f8cb5bb8c4bc7e83822e199c2.txt)
response
```
{
    "meta": {
        "url": "http://dev.ehealth.world/api/legal_entities",
        "type": "object",
        "request_id": "cefodgj42c3dst2278cm7vkq5oh1ei5f",
        "code": 500
    },
    "error": {
        "type": "internal_error"
    }
}
```

**Comment by lymychp** [comment]
@Troush please check logs for the `"request_id": "cefodgj42c3dst2278cm7vkq5oh1ei5f"`

**Comment by svetavedmed** [comment]
the same, sometimes 500
request [error-500.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46ed86882c90cefcdfb9fd0fe64de29b234324676b5ee17e29d4e22cee472352595a1afa46585e47afad887af0b56d62964e49bc8f3900299f7744eeaa880dbe08b0218e4f8cb2bf834ec4ea3e26ef99c2.txt)
```
{
    "meta": {
        "url": "http://dev.ehealth.world/api/legal_entities",
        "type": "object",
        "request_id": "pcqb56elq52spfap0c50kf6v60t3lip7",
        "code": 500
    },
    "error": {
        "type": "internal_error"
    }
}
```
